version: '3'

vars:
  NPX:
    sh: which -a bunx npx | grep -v "not found" | head -n 1

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code (e.g., protobufs)"
    deps:
      - gen-buf

  gen-buf:
    internal: true
    desc: "Generate protobufs"
    cmds:
      - buf generate

  lint:
    desc: "Lints the code"
    deps:
      - lint-buf
      - lint-go

  lint-buf:
    deps:
      - format
    cmds:
      - buf lint
      - buf format -w

  lint-go:
    deps:
      - format
    cmds:
      - golangci-lint run --verbose

  format:
    aliases: [fmt]
    run: once
    desc: "Formats all code"
    deps:
      - fmt-go
      - fmt-md

  fmt-md:
    run: once
    internal: true
    desc: "Format Markdown"
    cmds:
      - "{{.NPX}} prettier --write \"**/*.md\" --prose-wrap always"

  fmt-go:
    run: once
    internal: true
    desc: "Format Golang"
    cmds:
      - task: gofumpt
      - task: gci

  gofumpt:
    run: once
    internal: true
    desc: "Format Go code"
    cmds:
      - "go install mvdan.cc/gofumpt@latest"
      - "gofumpt -l -w ."

  gci:
    run: once
    internal: true
    desc: "Format Go imports"
    cmds:
      - |
        go install github.com/daixiang0/gci@latest ; \
        gci write --skip-generated \
          -s standard \
          -s default \
          -s "prefix(github.com/kevinmichaelchen/temporal-saga-grpc)" \
          .
