version: "3"

includes:
  buf:
    taskfile: ./taskfiles/buf.yml
  docs:
    taskfile: ./taskfiles/docs.yml
  go:
    taskfile: ./taskfiles/golang.yml
  run:
    taskfile: ./taskfiles/run.yml
  sqlboiler:
    taskfile: ./taskfiles/sqlboiler.yml

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code (e.g., protobufs)"
    deps:
      - buf:gen

  lint:
    desc: "Lints the code"
    deps:
      - buf:lint
      - go:lint

  format:
    aliases: [fmt]
    run: once
    desc: "Formats all code"
    deps:
      - buf:fmt
      - go:fmt
      - fmt-md

  fmt-md:
    run: once
    internal: true
    desc: "Format Markdown"
    cmds:
      - 'pkgx bunx prettier --write "**/*.md" --prose-wrap always'
