// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTodo struct {
	Text    string  `json:"text"`
	Subtext *string `json:"subtext"`
	UserID  string  `json:"userId"`
}

type Todo struct {
	ID      string  `json:"id"`
	Text    string  `json:"text"`
	Done    bool    `json:"done"`
	User    *User   `json:"user"`
	Subtext *string `json:"subtext"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
