// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: com/teachingstrategies/license/v1beta1/api.proto

package licensev1beta1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	v1beta1 "github.com/kevinmichaelchen/temporal-saga-grpc/internal/idl/com/teachingstrategies/license/v1beta1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// LicenseServiceName is the fully-qualified name of the LicenseService service.
	LicenseServiceName = "com.teachingstrategies.license.v1beta1.LicenseService"
)

// LicenseServiceClient is a client for the com.teachingstrategies.license.v1beta1.LicenseService
// service.
type LicenseServiceClient interface {
	CreateLicense(context.Context, *connect_go.Request[v1beta1.CreateLicenseRequest]) (*connect_go.Response[v1beta1.CreateLicenseResponse], error)
}

// NewLicenseServiceClient constructs a client for the
// com.teachingstrategies.license.v1beta1.LicenseService service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLicenseServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) LicenseServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &licenseServiceClient{
		createLicense: connect_go.NewClient[v1beta1.CreateLicenseRequest, v1beta1.CreateLicenseResponse](
			httpClient,
			baseURL+"/com.teachingstrategies.license.v1beta1.LicenseService/CreateLicense",
			opts...,
		),
	}
}

// licenseServiceClient implements LicenseServiceClient.
type licenseServiceClient struct {
	createLicense *connect_go.Client[v1beta1.CreateLicenseRequest, v1beta1.CreateLicenseResponse]
}

// CreateLicense calls com.teachingstrategies.license.v1beta1.LicenseService.CreateLicense.
func (c *licenseServiceClient) CreateLicense(ctx context.Context, req *connect_go.Request[v1beta1.CreateLicenseRequest]) (*connect_go.Response[v1beta1.CreateLicenseResponse], error) {
	return c.createLicense.CallUnary(ctx, req)
}

// LicenseServiceHandler is an implementation of the
// com.teachingstrategies.license.v1beta1.LicenseService service.
type LicenseServiceHandler interface {
	CreateLicense(context.Context, *connect_go.Request[v1beta1.CreateLicenseRequest]) (*connect_go.Response[v1beta1.CreateLicenseResponse], error)
}

// NewLicenseServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLicenseServiceHandler(svc LicenseServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	mux := http.NewServeMux()
	mux.Handle("/com.teachingstrategies.license.v1beta1.LicenseService/CreateLicense", connect_go.NewUnaryHandler(
		"/com.teachingstrategies.license.v1beta1.LicenseService/CreateLicense",
		svc.CreateLicense,
		opts...,
	))
	return "/com.teachingstrategies.license.v1beta1.LicenseService/", mux
}

// UnimplementedLicenseServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLicenseServiceHandler struct{}

func (UnimplementedLicenseServiceHandler) CreateLicense(context.Context, *connect_go.Request[v1beta1.CreateLicenseRequest]) (*connect_go.Response[v1beta1.CreateLicenseResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("com.teachingstrategies.license.v1beta1.LicenseService.CreateLicense is not implemented"))
}
