// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: license/v1beta1/api.proto

package licensev1beta1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateLicenseRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateLicenseRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateLicenseRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateLicenseRequestMultiError, or nil if none found.
func (m *CreateLicenseRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateLicenseRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := CreateLicenseRequestValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetFullName()) < 1 {
		err := CreateLicenseRequestValidationError{
			field:  "FullName",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CreateLicenseRequestMultiError(errors)
	}

	return nil
}

// CreateLicenseRequestMultiError is an error wrapping multiple validation
// errors returned by CreateLicenseRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateLicenseRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateLicenseRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateLicenseRequestMultiError) AllErrors() []error { return m }

// CreateLicenseRequestValidationError is the validation error returned by
// CreateLicenseRequest.Validate if the designated constraints aren't met.
type CreateLicenseRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateLicenseRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateLicenseRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateLicenseRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateLicenseRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateLicenseRequestValidationError) ErrorName() string {
	return "CreateLicenseRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateLicenseRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateLicenseRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateLicenseRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateLicenseRequestValidationError{}

// Validate checks the field values on CreateLicenseResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateLicenseResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateLicenseResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateLicenseResponseMultiError, or nil if none found.
func (m *CreateLicenseResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateLicenseResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return CreateLicenseResponseMultiError(errors)
	}

	return nil
}

// CreateLicenseResponseMultiError is an error wrapping multiple validation
// errors returned by CreateLicenseResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateLicenseResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateLicenseResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateLicenseResponseMultiError) AllErrors() []error { return m }

// CreateLicenseResponseValidationError is the validation error returned by
// CreateLicenseResponse.Validate if the designated constraints aren't met.
type CreateLicenseResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateLicenseResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateLicenseResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateLicenseResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateLicenseResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateLicenseResponseValidationError) ErrorName() string {
	return "CreateLicenseResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateLicenseResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateLicenseResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateLicenseResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateLicenseResponseValidationError{}
